#!/usr/bin/env ruby

require 'mqtt'

COLORS = { "white"  => "ffffff",
           "silver" => "c0c0c0",  
           "gray"   => "808080",
           "black"  => "000000",
           "red"    => "ff0000",
           "maroon" => "800000",
           "yellow" => "ffff00",
           "olive"  => "808000",
           "lime"   => "00ff00",
           "green"  => "008000",
           "aqua"   => "00ffff",
           "teal"   => "008080",
           "blue"   => "0000ff",
           "navy"   => "000080",
           "fuchsia"=> "ff00ff",
           "purple" => "800080" }

def publish(topic, payload)
  MQTT::Client.connect('mqtt://atlas.hasi:1883') do |c|
    c.publish(topic, payload)
  end
end

if ARGV[0] == "set"
  if ARGV[1] == "socket"
    if (0..3).include?(ARGV[2].to_i)
      if ARGV[3] == "on"      
        publish("hasi/sockets/#{ARGV[2]}/set_state", "on") 
      elsif ARGV[3] == "off"
        publish("hasi/sockets/#{ARGV[2]}/set_state", "off")
      else
        puts "Invalid status."
      end
    else
      puts "Invalid socket number."
    end
  elsif ARGV[1] == "strip"
    if COLORS[ARGV[2]].is_a? String
      publish("hasi/lights/stripes/set_rgb", COLORS[ARGV[2]])
    else
      puts "Invalid color name."
    end
  else
    puts "Invalid device."
  end
  
elsif ARGV[0] == "get"
  # TODO
else
  puts "Usage:"
  puts "hasimq-cli set socket{1..3} (on|off)"
  puts "hasimq-cli set strip (green|yellow|white...)"
  puts "--------------------------------------------"
end
